// Comprehensive menu items for each shop
const MENUS = {
  "Domino's Pizza": [
    { name: 'Margherita Pizza', description: 'Classic tomato sauce with mozzarella cheese', price: 149, category: 'Pizza', isVeg: true, isBestseller: true },
    { name: 'Farmhouse Pizza',  description: 'Loaded with fresh veggies and extra cheese', price: 229, category: 'Pizza', isVeg: true },
    { name: 'Peppy Paneer Pizza', description: 'Spicy paneer with capsicum and onions', price: 249, category: 'Pizza', isVeg: true, isBestseller: true },
    { name: 'Chicken Dominator', description: 'Loaded with 6 types of chicken toppings', price: 329, category: 'Pizza', isVeg: false },
    { name: 'Stuffed Garlic Breadsticks', description: 'Cheesy stuffed breadsticks with dip', price: 99, category: 'Sides', isVeg: true },
    { name: 'Pasta Italiano', description: 'Creamy white sauce pasta with veggies', price: 119, category: 'Pasta', isVeg: true },
  ],
  'Burger Singh': [
    { name: 'Amritsari Aloo Tikki Burger', description: 'Spiced potato tikki with desi sauces', price: 79, category: 'Burgers', isVeg: true, isBestseller: true },
    { name: 'Bhangra Paneer Burger', description: 'Grilled paneer with mint chutney', price: 99, category: 'Burgers', isVeg: true },
    { name: 'Maharaja Chicken Burger', description: 'Spicy chicken patty with coleslaw', price: 119, category: 'Burgers', isVeg: false, isBestseller: true },
    { name: 'Patiala Shahi Veg Burger', description: 'Double patty burger with special sauce', price: 129, category: 'Burgers', isVeg: true },
    { name: 'Masala Fries', description: 'Crispy fries with chaat masala', price: 59, category: 'Sides', isVeg: true },
    { name: 'Mango Shake', description: 'Thick chilled mango milkshake', price: 79, category: 'Drinks', isVeg: true },
  ],
  'Taste of Italy': [
    { name: 'Penne Arrabbiata', description: 'Spicy tomato sauce penne pasta', price: 149, category: 'Pasta', isVeg: true, isBestseller: true },
    { name: 'Spaghetti Aglio e Olio', description: 'Garlic, olive oil and parsley spaghetti', price: 159, category: 'Pasta', isVeg: true },
    { name: 'Quattro Formaggi Pizza', description: 'Four cheese premium pizza', price: 279, category: 'Pizza', isVeg: true, isBestseller: true },
    { name: 'Chicken Alfredo', description: 'Creamy alfredo with grilled chicken', price: 199, category: 'Pasta', isVeg: false },
    { name: 'Bruschetta', description: 'Toasted bread with tomato and basil', price: 89, category: 'Starters', isVeg: true },
    { name: 'Tiramisu', description: 'Classic Italian coffee dessert', price: 99, category: 'Desserts', isVeg: true },
  ],
  'Momos and More': [
    { name: 'Veg Steamed Momos (8pc)', description: 'Classic steamed veg dumplings with red chutney', price: 70, category: 'Momos', isVeg: true, isBestseller: true },
    { name: 'Chicken Steamed Momos (8pc)', description: 'Juicy chicken-filled steamed momos', price: 90, category: 'Momos', isVeg: false, isBestseller: true },
    { name: 'Paneer Fried Momos (8pc)', description: 'Crispy fried paneer momos', price: 100, category: 'Momos', isVeg: true },
    { name: 'Tandoori Momos (6pc)', description: 'Smoky tandoor-flavored momos', price: 110, category: 'Momos', isVeg: true, isBestseller: true },
    { name: 'Kurkure Momos', description: 'Crispy coated momos with spicy dip', price: 100, category: 'Momos', isVeg: true },
    { name: 'Thukpa Soup', description: 'Tibetan noodle soup with veggies', price: 80, category: 'Soup', isVeg: true },
  ],
  'Golden Fork': [
    { name: 'Veg Thali', description: 'Dal, sabzi, rice, roti and salad', price: 120, category: 'Thali', isVeg: true, isBestseller: true },
    { name: 'Chicken Thali', description: 'Chicken curry, rice, roti and salad', price: 160, category: 'Thali', isVeg: false },
    { name: 'Aloo Paratha', description: 'Stuffed paratha with butter and curd', price: 70, category: 'Breakfast', isVeg: true },
    { name: 'Paneer Butter Masala', description: 'Rich tomato-based paneer curry', price: 130, category: 'Main Course', isVeg: true, isBestseller: true },
    { name: 'Dal Makhani', description: 'Slow-cooked black dal with butter', price: 110, category: 'Main Course', isVeg: true },
    { name: 'Gulab Jamun (2pc)', description: 'Soft khoya dumplings in sugar syrup', price: 40, category: 'Desserts', isVeg: true },
  ],
  'Juice and Bites': [
    { name: 'Orange Juice (300ml)', description: 'Fresh squeezed orange juice', price: 40, category: 'Juices', isVeg: true, isBestseller: true },
    { name: 'Green Detox Juice', description: 'Spinach, cucumber, ginger and mint', price: 60, category: 'Juices', isVeg: true },
    { name: 'Mixed Fruit Smoothie', description: 'Seasonal fruits blended with milk', price: 80, category: 'Smoothies', isVeg: true, isBestseller: true },
    { name: 'Masala Nimbu Pani', description: 'Spiced fresh lemonade', price: 30, category: 'Drinks', isVeg: true },
    { name: 'Veggie Sandwich', description: 'Grilled sandwich with fresh veggies', price: 50, category: 'Snacks', isVeg: true },
    { name: 'Fruit Chaat', description: 'Seasoned mixed fruit bowl', price: 50, category: 'Snacks', isVeg: true },
  ],
  'Sip Sip Spot': [
    { name: 'Taro Milk Tea', description: 'Classic taro bubble tea with tapioca pearls', price: 99, category: 'Bubble Tea', isVeg: true, isBestseller: true },
    { name: 'Strawberry Matcha Latte', description: 'Layered matcha with strawberry syrup', price: 120, category: 'Latte', isVeg: true, isBestseller: true },
    { name: 'Brown Sugar Boba', description: 'Tiger-striped brown sugar bubble tea', price: 110, category: 'Bubble Tea', isVeg: true },
    { name: 'Mango Cold Coffee', description: 'Blended mango with cold brew coffee', price: 100, category: 'Cold Coffee', isVeg: true },
    { name: 'Oreo Shake', description: 'Thick Oreo cookie milkshake', price: 90, category: 'Shakes', isVeg: true },
    { name: 'Nutella Waffle', description: 'Crispy waffle drizzled with Nutella', price: 89, category: 'Desserts', isVeg: true },
  ],
  'Roll Corner': [
    { name: 'Egg Roll', description: 'Egg-wrapped kathi roll with chutney', price: 60, category: 'Rolls', isVeg: false, isBestseller: true },
    { name: 'Paneer Roll', description: 'Spiced paneer tikka roll', price: 80, category: 'Rolls', isVeg: true, isBestseller: true },
    { name: 'Chicken Tikka Roll', description: 'Tender chicken tikka wrapped in paratha', price: 100, category: 'Rolls', isVeg: false },
    { name: 'Veg Spring Roll (4pc)', description: 'Crispy veg-filled spring rolls', price: 60, category: 'Rolls', isVeg: true },
    { name: 'Aloo Matar Roll', description: 'Classic potato-peas stuffed roll', price: 50, category: 'Rolls', isVeg: true },
    { name: 'Special Masala Chaas', description: 'Spiced buttermilk', price: 25, category: 'Drinks', isVeg: true },
  ],
  "Wenky's": [
    { name: '2-Min Maggie', description: 'Classic Maggie noodles with masala', price: 40, category: 'Noodles', isVeg: true, isBestseller: true },
    { name: 'Cheese Maggie', description: 'Maggie loaded with extra cheese', price: 60, category: 'Noodles', isVeg: true, isBestseller: true },
    { name: 'Masala Papad', description: 'Crispy roasted papad with toppings', price: 30, category: 'Snacks', isVeg: true },
    { name: 'Bread Omelette', description: '2-egg omelette with toasted bread', price: 50, category: 'Snacks', isVeg: false },
    { name: 'Veg Puff', description: 'Baked puff pastry with veg filling', price: 25, category: 'Snacks', isVeg: true },
    { name: 'Cold Coffee (Small)', description: 'Classic cold coffee blend', price: 40, category: 'Drinks', isVeg: true },
  ],
  'Ice Cream Parlour': [
    { name: 'Butterscotch Scoop', description: '2 scoops of rich butterscotch ice cream', price: 60, category: 'Scoops', isVeg: true, isBestseller: true },
    { name: 'Chocolate Sundae', description: 'Chocolate ice cream with hot fudge and nuts', price: 90, category: 'Sundaes', isVeg: true, isBestseller: true },
    { name: 'Matka Kulfi', description: 'Traditional creamy kulfi in earthen pot', price: 50, category: 'Kulfi', isVeg: true },
    { name: 'Rainbow Sorbet', description: '3 flavour sorbet plate – mango, strawberry, kiwi', price: 80, category: 'Sorbet', isVeg: true },
    { name: 'Waffle Cone (2 scoops)', description: 'Choice of 2 flavours in waffle cone', price: 70, category: 'Cones', isVeg: true },
    { name: 'Banana Split', description: 'Banana, 3 scoops, whipped cream', price: 110, category: 'Sundaes', isVeg: true },
  ],
  'Basil': [
    { name: 'Caesar Salad', description: 'Romaine lettuce, croutons, parmesan dressing', price: 120, category: 'Salads', isVeg: true, isBestseller: true },
    { name: 'Greek Salad', description: 'Fresh veggies with feta cheese and olives', price: 130, category: 'Salads', isVeg: true },
    { name: 'Tomato Basil Soup', description: 'Classic creamy tomato basil soup', price: 80, category: 'Soups', isVeg: true, isBestseller: true },
    { name: 'Quinoa Power Bowl', description: 'Quinoa with roasted veggies and hummus', price: 160, category: 'Bowls', isVeg: true },
    { name: 'Avocado Toast', description: 'Smashed avocado on multigrain toast', price: 110, category: 'Snacks', isVeg: true },
    { name: 'Green Smoothie Bowl', description: 'Blended greens topped with seeds and fruits', price: 130, category: 'Bowls', isVeg: true },
  ],
  'Samosa Express': [
    { name: 'Aloo Samosa (2pc)', description: 'Classic fried potato samosa with chutney', price: 20, category: 'Samosa', isVeg: true, isBestseller: true },
    { name: 'Punjabi Samosa (2pc)', description: 'Large Punjabi style samosa', price: 30, category: 'Samosa', isVeg: true, isBestseller: true },
    { name: 'Samosa Chaat', description: 'Samosa topped with chole, chutneys and sev', price: 60, category: 'Chaat', isVeg: true },
    { name: 'Dahi Puri (6pc)', description: 'Puris filled with dahi and chutneys', price: 50, category: 'Chaat', isVeg: true },
    { name: 'Bhel Puri', description: 'Puffed rice mix with tamarind chutney', price: 40, category: 'Chaat', isVeg: true },
    { name: 'Aloo Chaat', description: 'Crispy potatoes with spicy chaat masala', price: 50, category: 'Chaat', isVeg: true },
  ],
  'Bunkers': [
    { name: 'Club Sandwich', description: 'Triple-decker sandwich with veggies and sauces', price: 90, category: 'Sandwiches', isVeg: true, isBestseller: true },
    { name: 'Veg Submarine', description: 'Long sub roll loaded with fresh veggies', price: 80, category: 'Sandwiches', isVeg: true },
    { name: 'Chicken Submarine', description: 'Grilled chicken sub with honey mustard', price: 110, category: 'Sandwiches', isVeg: false, isBestseller: true },
    { name: 'Paneer Tikka Sandwich', description: 'Grilled paneer with tandoori sauce', price: 90, category: 'Sandwiches', isVeg: true },
    { name: 'Hash Brown', description: 'Crispy potato hash brown patties (2)', price: 50, category: 'Sides', isVeg: true },
    { name: 'Oreo Shake', description: 'Crushed Oreo milkshake with cream', price: 80, category: 'Drinks', isVeg: true },
  ],
  'Chinese Wok': [
    { name: 'Hakka Noodles (Veg)', description: 'Tossed noodles with crisp vegetables', price: 80, category: 'Noodles', isVeg: true, isBestseller: true },
    { name: 'Chicken Hakka Noodles', description: 'Noodles with succulent chicken pieces', price: 110, category: 'Noodles', isVeg: false },
    { name: 'Veg Fried Rice', description: 'Chinese-style fried rice with veggies', price: 80, category: 'Rice', isVeg: true, isBestseller: true },
    { name: 'Veg Manchurian (Gravy)', description: 'Crispy veg balls in Manchurian sauce', price: 100, category: 'Gravy', isVeg: true },
    { name: 'Chicken Manchurian', description: 'Chicken in spicy tangy Manchurian sauce', price: 130, category: 'Gravy', isVeg: false },
    { name: 'Veg Spring Roll (4pc)', description: 'Golden fried spring rolls', price: 70, category: 'Starters', isVeg: true },
  ],
  'Healthy Bowl': [
    { name: 'Protein Power Bowl', description: 'Grilled tofu, quinoa, edamame and greens', price: 160, category: 'Bowls', isVeg: true, isBestseller: true },
    { name: 'Chicken Brown Rice Bowl', description: 'Lean chicken with brown rice and veggies', price: 180, category: 'Bowls', isVeg: false },
    { name: 'Acai Smoothie Bowl', description: 'Blended acai with granola and fruits', price: 150, category: 'Bowls', isVeg: true },
    { name: 'Kale Detox Juice', description: 'Kale, spinach, apple, ginger blend', price: 80, category: 'Juices', isVeg: true },
    { name: 'Vegan Wrap', description: 'Chickpea, avocado and roasted pepper wrap', price: 120, category: 'Wraps', isVeg: true, isBestseller: true },
    { name: 'Energy Date Balls (3pc)', description: 'No-sugar energy bites with nuts and dates', price: 60, category: 'Snacks', isVeg: true },
  ],
  'Chai Sutta Bar': [
    { name: 'Kulhad Chai (Regular)', description: 'Masala chai served in earthen kulhad', price: 20, category: 'Chai', isVeg: true, isBestseller: true },
    { name: 'Kulhad Chai (Special)', description: 'Extra spiced chai with ginger and elaichi', price: 25, category: 'Chai', isVeg: true, isBestseller: true },
    { name: 'Maggie in Kulhad', description: 'Spicy Maggie served in kulhad', price: 50, category: 'Snacks', isVeg: true, isBestseller: true },
    { name: 'Cheese Toast', description: 'Toasted bread with melted cheese', price: 40, category: 'Snacks', isVeg: true },
    { name: 'Kulhad Pizza', description: 'Mini loaded pizza in earthen cup', price: 70, category: 'Snacks', isVeg: true },
    { name: 'Cold Brew Coffee', description: 'Smooth cold brew served over ice', price: 60, category: 'Coffee', isVeg: true },
  ],
  'Juice Shop': [
    { name: 'Fresh Sugarcane Juice', description: 'Chilled sugarcane juice with ginger and lemon', price: 25, category: 'Juices', isVeg: true, isBestseller: true },
    { name: 'Watermelon Juice', description: 'Fresh watermelon juice with mint', price: 30, category: 'Juices', isVeg: true },
    { name: 'Mixed Veg Juice', description: 'Carrot, beetroot and tomato blend', price: 50, category: 'Juices', isVeg: true },
    { name: 'Mango Lassi', description: 'Thick mango yoghurt drink', price: 60, category: 'Lassi', isVeg: true, isBestseller: true },
    { name: 'Sweet Lassi', description: 'Chilled sweet yoghurt drink', price: 40, category: 'Lassi', isVeg: true },
    { name: 'Banana Shake', description: 'Thick banana milkshake', price: 55, category: 'Shakes', isVeg: true },
  ],
  'Trending Foods': [
    { name: 'Spicy Ramen', description: 'Japanese-Korean style ramen with broth', price: 120, category: 'Noodles', isVeg: false, isBestseller: true },
    { name: 'Loaded Poutine', description: 'Fries with gravy and paneer', price: 110, category: 'Fries', isVeg: true },
    { name: 'Korean Corn Dog', description: 'Battered hot dog on stick with toppings', price: 80, category: 'Snacks', isVeg: false, isBestseller: true },
    { name: 'Nutella Pancakes', description: 'Fluffy pancakes with Nutella spread', price: 90, category: 'Breakfast', isVeg: true },
    { name: 'Smash Burger', description: 'Smashed beef-style patty burger', price: 130, category: 'Burgers', isVeg: false },
    { name: 'Boba Milkshake', description: 'Classic milkshake with boba pearls', price: 90, category: 'Drinks', isVeg: true },
  ],
  'Tibet Food Shop': [
    { name: 'Thukpa (Veg)', description: 'Tibetan vegetable noodle soup', price: 80, category: 'Soup', isVeg: true, isBestseller: true },
    { name: 'Thukpa (Chicken)', description: 'Tibetan chicken noodle soup', price: 100, category: 'Soup', isVeg: false, isBestseller: true },
    { name: 'Tingmo', description: 'Steamed Tibetan bread served with curry', price: 60, category: 'Bread', isVeg: true },
    { name: 'Shapale (Meat Pie)', description: 'Fried Tibetan meat-filled pastry', price: 80, category: 'Snacks', isVeg: false },
    { name: 'Veg Momos (6pc)', description: 'Tibetan-style steamed dumplings', price: 60, category: 'Momos', isVeg: true },
    { name: 'Butter Tea (Poe Cha)', description: 'Traditional Tibetan salted butter tea', price: 30, category: 'Drinks', isVeg: true },
  ],
  'Maharaja Foods': [
    { name: 'Full Thali', description: 'Dal, 2 sabzis, roti, rice, pickle and curd', price: 130, category: 'Thali', isVeg: true, isBestseller: true },
    { name: 'Non-Veg Thali', description: 'Mutton curry, roti, rice, raita', price: 180, category: 'Thali', isVeg: false },
    { name: 'Butter Chicken', description: 'Creamy tomato-based chicken curry', price: 160, category: 'Curries', isVeg: false, isBestseller: true },
    { name: 'Shahi Paneer', description: 'Paneer in rich cream and cashew gravy', price: 140, category: 'Curries', isVeg: true },
    { name: 'Butter Naan (2pc)', description: 'Soft butter naans from tandoor', price: 40, category: 'Breads', isVeg: true },
    { name: 'Kheer', description: 'Creamy rice pudding with cardamom', price: 50, category: 'Desserts', isVeg: true },
  ],
  'PaniPuri Spot': [
    { name: 'Golgappa (6pc)', description: 'Crispy puris with spiced tamarind water', price: 30, category: 'Chaat', isVeg: true, isBestseller: true },
    { name: 'Dahi Golgappa (6pc)', description: 'Golgappa with sweet dahi and chutneys', price: 50, category: 'Chaat', isVeg: true, isBestseller: true },
    { name: 'Papdi Chaat', description: 'Crispy papdi with chickpeas and chutneys', price: 60, category: 'Chaat', isVeg: true },
    { name: 'Sev Puri', description: 'Flat puris with potatoes and sev', price: 50, category: 'Chaat', isVeg: true },
    { name: 'Bhel Puri', description: 'Puffed rice, veggies and tangy chutney', price: 40, category: 'Chaat', isVeg: true },
    { name: 'Sweet Corn Chaat', description: 'Masala sweet corn in cup', price: 40, category: 'Chaat', isVeg: true },
  ],
  'Pav Bhaji Corner': [
    { name: 'Pav Bhaji (2 pav)', description: 'Spiced veggie mash with buttered pav', price: 70, category: 'Main', isVeg: true, isBestseller: true },
    { name: 'Cheese Pav Bhaji', description: 'Pav bhaji topped with generous cheese', price: 90, category: 'Main', isVeg: true, isBestseller: true },
    { name: 'Vada Pav', description: 'Mumbai-style vada in pav with chutneys', price: 20, category: 'Snacks', isVeg: true },
    { name: 'Misal Pav', description: 'Sprouted moth curry with pav', price: 60, category: 'Main', isVeg: true },
    { name: 'Kolhapuri Bhaji Pav', description: 'Extra spicy Kolhapuri style bhaji', price: 80, category: 'Main', isVeg: true },
    { name: 'Sol Kadhi', description: 'Kokum and coconut milk digestive drink', price: 30, category: 'Drinks', isVeg: true },
  ],
  'Sandwich Hub': [
    { name: 'Grilled Veg Sandwich', description: 'Toasted sandwich with fresh vegetables', price: 50, category: 'Sandwiches', isVeg: true, isBestseller: true },
    { name: 'Cheese Grilled Sandwich', description: 'Melted cheese sandwich with veggies', price: 70, category: 'Sandwiches', isVeg: true, isBestseller: true },
    { name: 'Bombay Sandwich', description: 'Multi-layer sandwich with chutneys', price: 60, category: 'Sandwiches', isVeg: true },
    { name: 'Egg Sandwich', description: 'Egg mayo with lettuce sandwich', price: 60, category: 'Sandwiches', isVeg: false },
    { name: 'Mayonnaise Corn Sandwich', description: 'Sweet corn with mayo on toast', price: 65, category: 'Sandwiches', isVeg: true },
    { name: 'Milkshake (any flavour)', description: 'Choice of strawberry, chocolate or vanilla', price: 60, category: 'Drinks', isVeg: true },
  ],
  'Maggie Point': [
    { name: 'Regular Maggie', description: 'Basic Maggie noodles with masala', price: 30, category: 'Maggie', isVeg: true, isBestseller: true },
    { name: 'Loaded Cheese Maggie', description: 'Maggie loaded with cheddar and spices', price: 60, category: 'Maggie', isVeg: true, isBestseller: true },
    { name: 'Veg Maggie Soup', description: 'Soup-style Maggie with mixed veggies', price: 50, category: 'Maggie', isVeg: true },
    { name: 'Egg Maggie', description: 'Maggie with beaten egg mixed in', price: 50, category: 'Maggie', isVeg: false },
    { name: 'Maggie Sandwich', description: 'Grilled sandwich stuffed with Maggie', price: 60, category: 'Sandwiches', isVeg: true },
    { name: 'Hot Chocolate', description: 'Creamy hot chocolate with marshmallows', price: 40, category: 'Drinks', isVeg: true },
  ],
  'Mummy Di Roti': [
    { name: 'Aloo Paratha (2pc)', description: 'Homestyle aloo paratha with butter', price: 80, category: 'Paratha', isVeg: true, isBestseller: true },
    { name: 'Mooli Paratha (2pc)', description: 'Grated radish stuffed paratha', price: 80, category: 'Paratha', isVeg: true },
    { name: 'Gobhi Paratha (2pc)', description: 'Cauliflower stuffed paratha', price: 80, category: 'Paratha', isVeg: true, isBestseller: true },
    { name: 'Dal Tadka + Roti (3pc)', description: 'Homestyle yellow dal with fresh rotis', price: 90, category: 'Combos', isVeg: true },
    { name: 'Maa ki Dal + Roti (3pc)', description: 'Black lentil dal with rotis', price: 100, category: 'Combos', isVeg: true },
    { name: 'Lassi (Sweet)', description: 'Thick Punjabi sweet lassi', price: 50, category: 'Drinks', isVeg: true },
  ],
  'Chefs on Fire': [
    { name: 'Paneer Tikka (6pc)', description: 'Chargrilled marinated paneer pieces', price: 130, category: 'Starters', isVeg: true, isBestseller: true },
    { name: 'Dal Makhani', description: 'Slow cooked black dal with cream', price: 120, category: 'Dal', isVeg: true, isBestseller: true },
    { name: 'Chicken Tikka (6pc)', description: 'Juicy marinated chicken tikka from grill', price: 160, category: 'Starters', isVeg: false },
    { name: 'Butter Naan', description: 'Soft tandoor naan with butter', price: 30, category: 'Breads', isVeg: true },
    { name: 'Veg Biryani', description: 'Aromatic vegetable biryani with raita', price: 120, category: 'Rice', isVeg: true },
    { name: 'Kulfi Falooda', description: 'Creamy kulfi with vermicelli and rose syrup', price: 80, category: 'Desserts', isVeg: true },
  ],
  'Vada Pav Wale': [
    { name: 'Classic Vada Pav', description: 'Mumbai-style vada in soft pav with garlic chutney', price: 20, category: 'Vada Pav', isVeg: true, isBestseller: true },
    { name: 'Cheese Vada Pav', description: 'Vada pav with melted cheese slice', price: 35, category: 'Vada Pav', isVeg: true, isBestseller: true },
    { name: 'Schezwan Vada Pav', description: 'Spicy Schezwan chutney vada pav', price: 30, category: 'Vada Pav', isVeg: true },
    { name: 'Batata Vada (3pc)', description: 'Fried potato vada without pav', price: 30, category: 'Snacks', isVeg: true },
    { name: 'Masala Chai', description: 'Spiced ginger tea', price: 15, category: 'Drinks', isVeg: true },
    { name: 'Taak (Buttermilk)', description: 'Salted thin buttermilk', price: 20, category: 'Drinks', isVeg: true },
  ],
  'Rajma Chawal Corner': [
    { name: 'Rajma Chawal', description: 'Punjabi red kidney bean curry with rice', price: 90, category: 'Main', isVeg: true, isBestseller: true },
    { name: 'Rajma Chawal (Large)', description: 'Extra portion of rajma chawal', price: 120, category: 'Main', isVeg: true },
    { name: 'Rajma Chawal + Papad', description: 'Rajma chawal with crispy papad', price: 100, category: 'Combos', isVeg: true, isBestseller: true },
    { name: 'Plain Curd (Bowl)', description: 'Fresh homemade curd', price: 20, category: 'Sides', isVeg: true },
    { name: 'Achar (Pickle)', description: 'Mixed vegetable pickle', price: 10, category: 'Sides', isVeg: true },
    { name: 'Chaas (Buttermilk)', description: 'Light spiced buttermilk', price: 20, category: 'Drinks', isVeg: true },
  ],
  'South Indian Express': [
    { name: 'Masala Dosa', description: 'Crispy dosa with spiced potato filling and chutneys', price: 90, category: 'Dosa', isVeg: true, isBestseller: true },
    { name: 'Plain Dosa', description: 'Thin crispy rice-lentil crepe with sambar', price: 70, category: 'Dosa', isVeg: true },
    { name: 'Idli (3pc) + Vada (1pc)', description: 'Steamed idlis with fried vada and chutneys', price: 80, category: 'Breakfast', isVeg: true, isBestseller: true },
    { name: 'Medu Vada (2pc)', description: 'Crispy doughnut-shaped lentil vada', price: 60, category: 'Breakfast', isVeg: true },
    { name: 'Uttapam (Veg)', description: 'Thick rice pancake with vegetable toppings', price: 80, category: 'Breakfast', isVeg: true },
    { name: 'Filter Coffee', description: 'Authentic South Indian filter coffee', price: 30, category: 'Drinks', isVeg: true },
  ],
  'Deccan Dose': [
    { name: 'Pesarattu Dosa', description: 'Green moong dosa with ginger chutney', price: 90, category: 'Dosa', isVeg: true, isBestseller: true },
    { name: 'Mysore Masala Dosa', description: 'Red-chutney-spread spiced masala dosa', price: 110, category: 'Dosa', isVeg: true, isBestseller: true },
    { name: 'Set Dosa (3pc)', description: 'Soft thick set dosas with sambar and chutney', price: 80, category: 'Dosa', isVeg: true },
    { name: 'Bisi Bele Bath', description: 'South Indian rice-lentil porridge with veggies', price: 100, category: 'Main', isVeg: true },
    { name: 'Rava Kesari', description: 'Semolina-based sweet halwa with saffron', price: 50, category: 'Desserts', isVeg: true },
    { name: 'Degree Coffee', description: 'Hyderabadi strong degree filter coffee', price: 35, category: 'Drinks', isVeg: true },
  ],
  'Shanti Biryani': [
    { name: 'Veg Dum Biryani', description: 'Aromatic basmati rice with veggies and saffron', price: 130, category: 'Biryani', isVeg: true, isBestseller: true },
    { name: 'Chicken Dum Biryani', description: 'Slow-cooked bone-in chicken biryani', price: 180, category: 'Biryani', isVeg: false, isBestseller: true },
    { name: 'Mutton Biryani', description: 'Rich mutton dum biryani with raita', price: 230, category: 'Biryani', isVeg: false },
    { name: 'Paneer Biryani', description: 'Fragrant paneer biryani with fried onions', price: 160, category: 'Biryani', isVeg: true },
    { name: 'Raita', description: 'Cool yoghurt with cucumber and coriander', price: 30, category: 'Sides', isVeg: true },
    { name: 'Shahi Tukda', description: 'Fried bread soaked in saffron rabri', price: 80, category: 'Desserts', isVeg: true },
  ],
  'Mughlai Darbar': [
    { name: 'Murgh Musallam', description: 'Whole roasted chicken in rich Mughlai gravy', price: 280, category: 'Main Course', isVeg: false, isBestseller: true },
    { name: 'Dal Bukhara', description: 'Slow-cooked black lentils overnight', price: 150, category: 'Dal', isVeg: true, isBestseller: true },
    { name: 'Seekh Kebab (4pc)', description: 'Minced meat kebabs with mint chutney', price: 180, category: 'Kebabs', isVeg: false },
    { name: 'Paneer Tikka Masala', description: 'Charred paneer in smoky tomato gravy', price: 170, category: 'Main Course', isVeg: true },
    { name: 'Roomali Roti (2pc)', description: 'Thin handkerchief bread', price: 40, category: 'Breads', isVeg: true },
    { name: 'Phirni', description: 'Set rice pudding with pistachios', price: 70, category: 'Desserts', isVeg: true },
  ],
  'Punjabi Dhaba': [
    { name: 'Butter Chicken + Roti (3pc)', description: 'Classic butter chicken with fresh rotis', price: 180, category: 'Combos', isVeg: false, isBestseller: true },
    { name: 'Saag + Makki Di Roti', description: 'Sarson ka saag with cornflour bread', price: 120, category: 'Main', isVeg: true, isBestseller: true },
    { name: 'Lassi (Full)', description: 'Thick Punjabi lassi in large glass', price: 60, category: 'Drinks', isVeg: true },
    { name: 'Tandoori Chicken (Half)', description: 'Marinated half-chicken from tandoor', price: 200, category: 'Starters', isVeg: false },
    { name: 'Paneer Lababdar', description: 'Rich cashew and tomato paneer gravy', price: 150, category: 'Main', isVeg: true },
    { name: 'Malpua with Rabri', description: 'Fried sweet pancake with thickened milk', price: 80, category: 'Desserts', isVeg: true },
  ],
  'Nescafe': [
    { name: 'Hot Coffee (Regular)', description: 'Classic Nescafe hot coffee', price: 40, category: 'Coffee', isVeg: true, isBestseller: true },
    { name: 'Cappuccino', description: 'Frothy cappuccino with warm milk', price: 60, category: 'Coffee', isVeg: true },
    { name: 'Cold Coffee', description: 'Chilled blended Nescafe coffee', price: 60, category: 'Coffee', isVeg: true, isBestseller: true },
    { name: 'Chocolate Croissant', description: 'Buttery croissant with chocolate filling', price: 50, category: 'Bakery', isVeg: true },
    { name: 'Muffin', description: 'Assorted flavour muffins', price: 40, category: 'Bakery', isVeg: true },
    { name: 'Tea (Regular)', description: 'Simple hot tea', price: 20, category: 'Tea', isVeg: true },
  ],
  'HorseShoe Cafe': [
    { name: 'Belgian Waffles', description: 'Thick Belgian waffles with berries and cream', price: 150, category: 'Waffles', isVeg: true, isBestseller: true },
    { name: 'Flat White', description: 'Espresso with steamed microfoam milk', price: 120, category: 'Coffee', isVeg: true, isBestseller: true },
    { name: 'Eggs Benedict', description: 'Poached eggs on English muffin with hollandaise', price: 160, category: 'Breakfast', isVeg: false },
    { name: 'Avocado Toast', description: 'Multigrain toast with smashed avocado and eggs', price: 140, category: 'Breakfast', isVeg: true },
    { name: 'Blueberry Cheesecake', description: 'Creamy NY-style cheesecake with blueberries', price: 120, category: 'Desserts', isVeg: true },
    { name: 'Iced Americano', description: 'Double espresso over ice', price: 100, category: 'Coffee', isVeg: true },
  ],
  'Brew Lab Cafe': [
    { name: 'Pour Over Coffee', description: 'Slow-drip specialty pour-over coffee', price: 130, category: 'Coffee', isVeg: true, isBestseller: true },
    { name: 'Cold Brew (12oz)', description: 'Smooth 24-hour cold-brewed coffee', price: 120, category: 'Coffee', isVeg: true, isBestseller: true },
    { name: 'Cortado', description: 'Equal parts espresso and warm milk', price: 100, category: 'Coffee', isVeg: true },
    { name: 'Chai Latte', description: 'Spiced masala chai with steamed oat milk', price: 110, category: 'Tea', isVeg: true },
    { name: 'Overnight Oats', description: 'Cold-soaked oats with chia and berry compote', price: 120, category: 'Breakfast', isVeg: true },
    { name: 'Almond Croissant', description: 'Flaky croissant stuffed with almond cream', price: 90, category: 'Bakery', isVeg: true },
  ],
};

module.exports = { MENUS };
